// backend/src/models/store.js
// In-memory data store — same seed data as frontend-html/shared.js
// In production you would replace this with a real database (PostgreSQL, MongoDB, etc.)

const { v4: uuidv4 } = require('uuid');

// ── Seed Users ──────────────────────────────────────────────────────────────
const users = [
  {
    id: 'admin-001',
    name: 'Admin User',
    firstName: 'Admin',
    lastName: 'User',
    email: 'admin@eduhub.ac.za',
    role: 'admin',
    status: 'active',
    createdAt: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'lec-001',
    name: 'Dr. Sarah Mokoena',
    firstName: 'Sarah',
    lastName: 'Mokoena',
    email: 'smokoena@eduhub.ac.za',
    role: 'lecturer',
    status: 'active',
    createdAt: new Date('2024-01-01').toISOString(),
  },
];

// Passwords stored separately (plain text for demo — use bcrypt in production)
const passwords = {
  'admin@eduhub.ac.za':    'admin123',
  'smokoena@eduhub.ac.za': 'lec123',
};

// ── Qualifications (same as QUALIFICATIONS in shared.js) ───────────────────
const qualifications = [
  {code:'BSc IT',name:'Bachelor of Science in Information Technology',faculty:'Faculty of Information Technology',duration:'3 Years',fee:45000,modules:[{code:'BSCIT1101',name:'Introduction to Programming',credits:15,semester:1,year:1},{code:'BSCIT1102',name:'Computer Architecture & Organisation',credits:15,semester:1,year:1},{code:'BSCIT1103',name:'Mathematics for Computing',credits:15,semester:1,year:1},{code:'BSCIT1204',name:'Web Development Fundamentals',credits:15,semester:2,year:1},{code:'BSCIT1205',name:'Database Design & Management',credits:15,semester:2,year:1},{code:'BSCIT1206',name:'Networking Fundamentals',credits:15,semester:2,year:1},{code:'BSCIT2107',name:'Object-Oriented Programming',credits:15,semester:1,year:2},{code:'BSCIT2108',name:'Systems Analysis & Design',credits:15,semester:1,year:2},{code:'BSCIT2109',name:'Data Structures & Algorithms',credits:15,semester:1,year:2},{code:'BSCIT2210',name:'Cyber Security Fundamentals',credits:15,semester:2,year:2},{code:'BSCIT2211',name:'Cloud Computing',credits:15,semester:2,year:2},{code:'BSCIT2212',name:'Internet of Things',credits:15,semester:2,year:2},{code:'BSCIT3113',name:'Business Intelligence & Data Analytics',credits:15,semester:1,year:3},{code:'BSCIT3114',name:'Mobile Computing & Applications',credits:15,semester:1,year:3},{code:'BSCIT3115',name:'IT Project Management',credits:15,semester:1,year:3},{code:'BSCIT3216',name:'Digital Applications Development',credits:15,semester:2,year:3},{code:'BSCIT3217',name:'Work Integrated Learning',credits:15,semester:2,year:3},{code:'BSCIT3218',name:'IT Research Project',credits:15,semester:2,year:3}]},
  {code:'Dip IT',name:'Diploma in Information Technology',faculty:'Faculty of Information Technology',duration:'3 Years',fee:42000,modules:[{code:'DIT1101',name:'Introduction to IT',credits:15,semester:1,year:1},{code:'DIT1102',name:'Programming Logic & Design',credits:15,semester:1,year:1},{code:'DIT1103',name:'Computer Hardware & Software',credits:15,semester:1,year:1},{code:'DIT1204',name:'Database Fundamentals',credits:15,semester:2,year:1},{code:'DIT1205',name:'Web Design & Development',credits:15,semester:2,year:1},{code:'DIT1206',name:'Business Communication',credits:15,semester:2,year:1},{code:'DIT2107',name:'Network Administration',credits:15,semester:1,year:2},{code:'DIT2108',name:'Application Programming',credits:15,semester:1,year:2},{code:'DIT2109',name:'Operating Systems Administration',credits:15,semester:1,year:2},{code:'DIT2210',name:'IT Service Management',credits:15,semester:2,year:2},{code:'DIT2211',name:'Python Development',credits:15,semester:2,year:2},{code:'DIT2212',name:'Systems Security',credits:15,semester:2,year:2},{code:'DIT3113',name:'Advanced Networking & Infrastructure',credits:15,semester:1,year:3},{code:'DIT3114',name:'Database Administration',credits:15,semester:1,year:3},{code:'DIT3115',name:'Software Engineering',credits:15,semester:1,year:3},{code:'DIT3216',name:'Work Integrated Learning',credits:15,semester:2,year:3},{code:'DIT3217',name:'IT Governance & Compliance',credits:15,semester:2,year:3},{code:'DIT3218',name:'Emerging Technologies',credits:15,semester:2,year:3}]},
  {code:'HC IT',name:'Higher Certificate in Information Technology',faculty:'Faculty of Information Technology',duration:'1 Year',fee:28000,modules:[{code:'HCIT1101',name:'IT Fundamentals',credits:15,semester:1,year:1},{code:'HCIT1102',name:'Introduction to Programming',credits:15,semester:1,year:1},{code:'HCIT1103',name:'Computer Networks Basics',credits:15,semester:1,year:1},{code:'HCIT1204',name:'Systems Development',credits:15,semester:2,year:1},{code:'HCIT1205',name:'Technical Support Fundamentals',credits:15,semester:2,year:1},{code:'HCIT1206',name:'Web Development Basics',credits:15,semester:2,year:1}]},
  {code:'HC CF',name:'Higher Certificate in Computer Forensics',faculty:'Faculty of Information Technology',duration:'1 Year',fee:28000,modules:[{code:'HCCF1101',name:'Introduction to Cybercrime & Law',credits:15,semester:1,year:1},{code:'HCCF1102',name:'Digital Evidence & Acquisition',credits:15,semester:1,year:1},{code:'HCCF1103',name:'Computer Forensics Fundamentals',credits:15,semester:1,year:1},{code:'HCCF1204',name:'Information Security Management',credits:15,semester:2,year:1},{code:'HCCF1205',name:'Cybercrime Investigation Techniques',credits:15,semester:2,year:1},{code:'HCCF1206',name:'Forensic Reporting & Documentation',credits:15,semester:2,year:1}]},
  {code:'BSc Hons IT',name:'BSc Honours in Information Technology',faculty:'Faculty of Information Technology',duration:'1 Year',fee:48000,modules:[{code:'BSCHIT1101',name:'Advanced Research Methodology',credits:15,semester:1,year:1},{code:'BSCHIT1102',name:'IT Leadership & Governance',credits:15,semester:1,year:1},{code:'BSCHIT1203',name:'Advanced Software Engineering',credits:15,semester:2,year:1},{code:'BSCHIT1204',name:'Research Project & Dissertation',credits:15,semester:2,year:1}]},
  {code:'BCom',name:'Bachelor of Commerce',faculty:'Faculty of Business & Management Sciences',duration:'3 Years',fee:42000,modules:[{code:'BCOM1101',name:'Business Communication',credits:15,semester:1,year:1},{code:'BCOM1102',name:'Principles of Management',credits:15,semester:1,year:1},{code:'BCOM1103',name:'Financial Accounting',credits:15,semester:1,year:1},{code:'BCOM1204',name:'Economics I',credits:15,semester:2,year:1},{code:'BCOM1205',name:'Business Mathematics & Statistics',credits:15,semester:2,year:1},{code:'BCOM1206',name:'Marketing Fundamentals',credits:15,semester:2,year:1},{code:'BCOM2107',name:'Cost & Management Accounting',credits:15,semester:1,year:2},{code:'BCOM2108',name:'Human Resource Management',credits:15,semester:1,year:2},{code:'BCOM2109',name:'Business Law',credits:15,semester:1,year:2},{code:'BCOM2210',name:'Financial Management',credits:15,semester:2,year:2},{code:'BCOM2211',name:'Marketing Management',credits:15,semester:2,year:2},{code:'BCOM2212',name:'Operations Management',credits:15,semester:2,year:2},{code:'BCOM3113',name:'Strategic Management',credits:15,semester:1,year:3},{code:'BCOM3114',name:'Entrepreneurship & Innovation',credits:15,semester:1,year:3},{code:'BCOM3115',name:'Supply Chain Management',credits:15,semester:1,year:3},{code:'BCOM3216',name:'Corporate Governance & Ethics',credits:15,semester:2,year:3},{code:'BCOM3217',name:'International Business',credits:15,semester:2,year:3},{code:'BCOM3218',name:'Business Research Project',credits:15,semester:2,year:3}]},
  {code:'BBA',name:'Bachelor of Business Administration',faculty:'Faculty of Business & Management Sciences',duration:'3 Years',fee:42000,modules:[{code:'BBA1101',name:'Business Communication',credits:15,semester:1,year:1},{code:'BBA1102',name:'Organisational Behaviour',credits:15,semester:1,year:1},{code:'BBA1103',name:'Business Mathematics',credits:15,semester:1,year:1},{code:'BBA1204',name:'Introduction to Economics',credits:15,semester:2,year:1},{code:'BBA1205',name:'Business Computing',credits:15,semester:2,year:1},{code:'BBA1206',name:'Marketing Principles',credits:15,semester:2,year:1},{code:'BBA2107',name:'Financial Accounting',credits:15,semester:1,year:2},{code:'BBA2108',name:'Human Resource Management',credits:15,semester:1,year:2},{code:'BBA2109',name:'Business Law & Ethics',credits:15,semester:1,year:2},{code:'BBA2210',name:'Project Management',credits:15,semester:2,year:2},{code:'BBA2211',name:'Operations & Supply Chain',credits:15,semester:2,year:2},{code:'BBA2212',name:'Entrepreneurship',credits:15,semester:2,year:2},{code:'BBA3113',name:'Strategic Management',credits:15,semester:1,year:3},{code:'BBA3114',name:'Leadership & Change Management',credits:15,semester:1,year:3},{code:'BBA3115',name:'Digital Business & Innovation',credits:15,semester:1,year:3},{code:'BBA3216',name:'International Business Management',credits:15,semester:2,year:3},{code:'BBA3217',name:'Corporate Governance',credits:15,semester:2,year:3},{code:'BBA3218',name:'Business Research Project',credits:15,semester:2,year:3}]},
  {code:'BPM',name:'Bachelor of Public Management',faculty:'Faculty of Business & Management Sciences',duration:'3 Years',fee:38000,modules:[{code:'BPM1101',name:'Introduction to Public Administration',credits:15,semester:1,year:1},{code:'BPM1102',name:'Public Policy Fundamentals',credits:15,semester:1,year:1},{code:'BPM1103',name:'Government & Governance',credits:15,semester:1,year:1},{code:'BPM1204',name:'Public Sector Economics',credits:15,semester:2,year:1},{code:'BPM1205',name:'Public Finance & Budgeting',credits:15,semester:2,year:1},{code:'BPM1206',name:'Communication for Public Sector',credits:15,semester:2,year:1},{code:'BPM2107',name:'Public Sector HR Management',credits:15,semester:1,year:2},{code:'BPM2108',name:'Local Government Management',credits:15,semester:1,year:2},{code:'BPM2109',name:'Public Law & Administration',credits:15,semester:1,year:2},{code:'BPM2210',name:'Service Delivery Management',credits:15,semester:2,year:2},{code:'BPM2211',name:'Development Studies',credits:15,semester:2,year:2},{code:'BPM2212',name:'Research Methods in Public Sector',credits:15,semester:2,year:2},{code:'BPM3113',name:'Public Sector Strategic Planning',credits:15,semester:1,year:3},{code:'BPM3114',name:'Performance Management in Public Sector',credits:15,semester:1,year:3},{code:'BPM3115',name:'Intergovernmental Relations',credits:15,semester:1,year:3},{code:'BPM3216',name:'Policy Implementation & Evaluation',credits:15,semester:2,year:3},{code:'BPM3217',name:'Public Sector Entrepreneurship',credits:15,semester:2,year:3},{code:'BPM3218',name:'Research Project',credits:15,semester:2,year:3}]},
  {code:'DBA',name:'Diploma in Business Administration',faculty:'Faculty of Business & Management Sciences',duration:'3 Years',fee:38000,modules:[{code:'DBA1101',name:'Business Communication',credits:15,semester:1,year:1},{code:'DBA1102',name:'Principles of Management',credits:15,semester:1,year:1},{code:'DBA1103',name:'Business Mathematics',credits:15,semester:1,year:1},{code:'DBA1204',name:'Introduction to Accounting',credits:15,semester:2,year:1},{code:'DBA1205',name:'Marketing Basics',credits:15,semester:2,year:1},{code:'DBA1206',name:'Business Computing',credits:15,semester:2,year:1},{code:'DBA2107',name:'Financial Management',credits:15,semester:1,year:2},{code:'DBA2108',name:'Human Resources Fundamentals',credits:15,semester:1,year:2},{code:'DBA2109',name:'Business Law',credits:15,semester:1,year:2},{code:'DBA2210',name:'Supply Chain & Procurement',credits:15,semester:2,year:2},{code:'DBA2211',name:'Entrepreneurship',credits:15,semester:2,year:2},{code:'DBA2212',name:'Operations Management',credits:15,semester:2,year:2},{code:'DBA3113',name:'Strategic Business Management',credits:15,semester:1,year:3},{code:'DBA3114',name:'Leadership & Organisational Development',credits:15,semester:1,year:3},{code:'DBA3115',name:'Business Research Methods',credits:15,semester:1,year:3},{code:'DBA3216',name:'Work Integrated Learning',credits:15,semester:2,year:3},{code:'DBA3217',name:'Digital Business Transformation',credits:15,semester:2,year:3},{code:'DBA3218',name:'Business Research Project',credits:15,semester:2,year:3}]},
  {code:'DLGM',name:'Diploma in Local Government Management',faculty:'Faculty of Business & Management Sciences',duration:'3 Years',fee:36000,modules:[{code:'DLGM1101',name:'Introduction to Local Government',credits:15,semester:1,year:1},{code:'DLGM1102',name:'Public Administration Foundations',credits:15,semester:1,year:1},{code:'DLGM1103',name:'Municipal Finance Basics',credits:15,semester:1,year:1},{code:'DLGM1204',name:'Local Government Legislation',credits:15,semester:2,year:1},{code:'DLGM1205',name:'Integrated Development Planning',credits:15,semester:2,year:1},{code:'DLGM1206',name:'Community Development',credits:15,semester:2,year:1},{code:'DLGM2107',name:'Municipal HR Management',credits:15,semester:1,year:2},{code:'DLGM2108',name:'Service Delivery & Performance',credits:15,semester:1,year:2},{code:'DLGM2109',name:'Local Government Finance',credits:15,semester:1,year:2},{code:'DLGM2210',name:'Policy Process & Implementation',credits:15,semester:2,year:2},{code:'DLGM2211',name:'Ward Committee Systems',credits:15,semester:2,year:2},{code:'DLGM2212',name:'Municipal Governance',credits:15,semester:2,year:2},{code:'DLGM3113',name:'Advanced Municipal Management',credits:15,semester:1,year:3},{code:'DLGM3114',name:'Local Economic Development',credits:15,semester:1,year:3},{code:'DLGM3115',name:'Environmental Management in LGM',credits:15,semester:1,year:3},{code:'DLGM3216',name:'Work Integrated Learning',credits:15,semester:2,year:3},{code:'DLGM3217',name:'Research Methods in Public Management',credits:15,semester:2,year:3},{code:'DLGM3218',name:'Applied Research Project',credits:15,semester:2,year:3}]},
  {code:'HCBA',name:'Higher Certificate in Business Administration',faculty:'Faculty of Business & Management Sciences',duration:'1 Year',fee:26000,modules:[{code:'HCBA1101',name:'Business Communication',credits:15,semester:1,year:1},{code:'HCBA1102',name:'Introduction to Management',credits:15,semester:1,year:1},{code:'HCBA1103',name:'Basic Financial Literacy',credits:15,semester:1,year:1},{code:'HCBA1204',name:'Customer Service & Relations',credits:15,semester:2,year:1},{code:'HCBA1205',name:'Office Technology & Computing',credits:15,semester:2,year:1},{code:'HCBA1206',name:'Work Integrated Learning',credits:15,semester:2,year:1}]},
  {code:'HCOA',name:'Higher Certificate in Office Administration',faculty:'Faculty of Business & Management Sciences',duration:'1 Year',fee:26000,modules:[{code:'HCOA1101',name:'Office Administration Principles',credits:15,semester:1,year:1},{code:'HCOA1102',name:'Business English & Communication',credits:15,semester:1,year:1},{code:'HCOA1103',name:'Computer Applications & Office Software',credits:15,semester:1,year:1},{code:'HCOA1204',name:'Records & Information Management',credits:15,semester:2,year:1},{code:'HCOA1205',name:'Administrative Support Services',credits:15,semester:2,year:1},{code:'HCOA1206',name:'Work Integrated Learning',credits:15,semester:2,year:1}]},
  {code:'HCLGM',name:'Higher Certificate in Local Government Management',faculty:'Faculty of Business & Management Sciences',duration:'1 Year',fee:26000,modules:[{code:'HCLGM1101',name:'Introduction to Local Government',credits:15,semester:1,year:1},{code:'HCLGM1102',name:'Public Sector Administration',credits:15,semester:1,year:1},{code:'HCLGM1103',name:'Municipal Finance Fundamentals',credits:15,semester:1,year:1},{code:'HCLGM1204',name:'Community Engagement & Development',credits:15,semester:2,year:1},{code:'HCLGM1205',name:'Service Delivery Basics',credits:15,semester:2,year:1},{code:'HCLGM1206',name:'Work Integrated Learning',credits:15,semester:2,year:1}]},
  {code:'HC RPLA',name:'Higher Certificate in Recognition of Prior Learning Activities',faculty:'Faculty of Business & Management Sciences',duration:'1 Year',fee:24000,modules:[{code:'HCRPLA1101',name:'Principles of RPL in Higher Education',credits:15,semester:1,year:1},{code:'HCRPLA1102',name:'Portfolio Preparation & Assessment',credits:15,semester:1,year:1},{code:'HCRPLA1203',name:'RPL Facilitation Practice',credits:15,semester:2,year:1},{code:'HCRPLA1204',name:'Work Integrated Learning in RPL',credits:15,semester:2,year:1}]},
  {code:'MBA',name:'Master of Business Administration',faculty:'Faculty of Business & Management Sciences',duration:'2 Years',fee:68000,modules:[{code:'MBA1101',name:'Advanced Business Strategy',credits:15,semester:1,year:1},{code:'MBA1102',name:'Leadership in the 4th Industrial Revolution',credits:15,semester:1,year:1},{code:'MBA1103',name:'Advanced Financial Management',credits:15,semester:1,year:1},{code:'MBA1204',name:'Digital Transformation & Innovation',credits:15,semester:2,year:1},{code:'MBA1205',name:'Research Methodology',credits:15,semester:2,year:1},{code:'MBA1206',name:'Advanced Marketing Strategy',credits:15,semester:2,year:1},{code:'MBA2107',name:'Big Data & Analytics for Managers',credits:15,semester:1,year:2},{code:'MBA2108',name:'Entrepreneurship & Venture Capital',credits:15,semester:1,year:2},{code:'MBA2109',name:'Corporate Governance & Business Ethics',credits:15,semester:1,year:2},{code:'MBA2210',name:'MBA Research Project / Dissertation',credits:15,semester:2,year:2}]},
  {code:'PGDip Mgt',name:'Postgraduate Diploma in Management',faculty:'Faculty of Business & Management Sciences',duration:'1 Year',fee:48000,modules:[{code:'PGDM1101',name:'Management Principles & Practices',credits:15,semester:1,year:1},{code:'PGDM1102',name:'Organisational Leadership',credits:15,semester:1,year:1},{code:'PGDM1203',name:'Strategic Human Resource Management',credits:15,semester:2,year:1},{code:'PGDM1204',name:'Applied Management Research Project',credits:15,semester:2,year:1}]},
];
// ── Runtime collections ─────────────────────────────────────────────────────
const applications   = [];
const registrations  = [];
const notifications  = [];
const auditLogs      = [];
const sessions       = {}; // token → userId

// ── Helper: generate student ID ─────────────────────────────────────────────
function generateStudentId() {
  const year  = new Date().getFullYear();
  const short = String(year).slice(2);
  const rand  = Math.floor(1000000 + Math.random() * 9000000);
  return `SD${short}/${year}/${rand}`;
}

// ── Helper: safe user (strip password) ─────────────────────────────────────
function safeUser(u) {
  if (!u) return null;
  const { password, ...rest } = u;
  return rest;
}

module.exports = {
  users, passwords, qualifications,
  applications, registrations, notifications, auditLogs, sessions,
  generateStudentId, safeUser, uuidv4,
};
