$kind: http-request
name: Create Application
method: POST
url: '{{base_url}}/applications'
order: 1000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "campus_id": "{{campus_id}}",
      "qualification_id": "{{qualification_id}}",
      "first_name": "Jane",
      "last_name": "Doe",
      "email": "jane.doe@example.com",
      "phone": "0821234567",
      "id_number": "9001010000000",
      "tc_accepted": true,
      "status": "pending",
      "application_type": "new",
      "admission_for": "1st Year"
    }
